---
- name: Ensure Nginx package
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes
  register: nginx_install_status

- name: debug the previous task
  debug:
    var: nginx_install_status

- set_fact:
    numbers: "{{ number[inventory_hostname] | default(0) }}"

- name: add custom html page
  template:
    src: templates/welcome.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: remove default index html file
  file:
    path: /var/www/html/index.nginx-debian.html
    state: absent

- name: start and enable nginx
  systemd_service:
    name: nginx
    state: started
    enabled: true
