name: ping

on:
  workflow_dispatch:

jobs:
  ansible-ping:
    runs-on: all
    container:
      image: ansible/ansible:latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: add ssh private key
        run: |
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > ansible
          chmod 600 ansible_key

      - name: ping hosts using ansible
        run: |
          ansible all -m ping -i hosts
        
